<a href="https://colab.research.google.com/github/HasibAlMuzdadid/Data-Science-Projects/blob/main/mean%20variance%20standard%20deviation%20calculator/mean_variance_standard_deviation_calculator.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Mean Variance Standard Deviation calculator**

Create a function named calculate() that uses Numpy to output the mean, variance, standard deviation, max, min, and sum of the rows, columns, and elements in a 3 x 3 matrix.

The input of the function should be a list containing 9 digits. The function should convert the list into a 3 x 3 Numpy array, and then return a dictionary containing the mean, variance, standard deviation, max, min, and sum along both axes and for the flattened matrix.


If a list containing less than 9 elements is passed into the function, it should raise a ValueError exception with the message: "List must contain nine numbers." The values in the returned dictionary should be lists and not Numpy arrays.

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
def calculate(input_list):
    if len(input_list) != 9:
        raise ValueError("List must contain nine numbers.")

    flat_matrix = np.array(input_list)
    print(f"One Dimensional : \n{flat_matrix}")
    
    converted_matrix = flat_matrix.reshape((3,3))
    print(f"\n\nAfter converting to 3x3 matrix : \n{converted_matrix}")
    
    print(f"\n\n'mean': [{list(np.mean(converted_matrix, axis = 0))},{list(np.mean(converted_matrix, axis = 1))}, {np.mean(flat_matrix)}]")
    print(f"'variance': [{list(np.var(converted_matrix, axis = 0))},{list(np.var(converted_matrix, axis = 1))}, {np.var(flat_matrix)}]")
    print(f"'standard deviation': [{list(np.std(converted_matrix, axis = 0))},{list(np.std(converted_matrix, axis = 1))}, {np.std(flat_matrix)}]")
    print(f"'max': [{list(np.max(converted_matrix, axis = 0))},{list(np.max(converted_matrix, axis = 1))}, {np.max(flat_matrix)}]")
    print(f"'min': [{list(np.min(converted_matrix, axis = 0))},{list(np.min(converted_matrix, axis = 1))}, {np.min(flat_matrix)}]")
    print(f"'sum': [{list(np.sum(converted_matrix, axis = 0))},{list(np.sum(converted_matrix, axis = 1))}, {np.sum(flat_matrix)}]\n\n")


    print("By using Dictionary:")
    calculations = {
        'mean': [list(np.mean(converted_matrix, axis = 0)),list(np.mean(converted_matrix, axis = 1)), np.mean(flat_matrix)],
        'variance': [list(np.var(converted_matrix, axis = 0)),list(np.var(converted_matrix, axis = 1)), np.var(flat_matrix)],
        'standard deviation': [list(np.std(converted_matrix, axis = 0)),list(np.std(converted_matrix, axis = 1)), np.std(flat_matrix)],
        'max': [list(np.max(converted_matrix, axis = 0)),list(np.max(converted_matrix, axis = 1)), np.max(flat_matrix)],
        'min': [list(np.min(converted_matrix, axis = 0)),list(np.min(converted_matrix, axis = 1)), np.min(flat_matrix)],
        'sum': [list(np.sum(converted_matrix, axis = 0)),list(np.sum(converted_matrix, axis = 1)), np.sum(flat_matrix)]
    }

    return (calculations)

In [ ]:
print(calculate([0,1,2,3,4,5,6,7,8]))

One Dimensional : 
[0 1 2 3 4 5 6 7 8]


After converting to 3x3 matrix : 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


'mean': [[3.0, 4.0, 5.0],[1.0, 4.0, 7.0], 4.0]
'variance': [[6.0, 6.0, 6.0],[0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667]
'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178],[0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611]
'max': [[6, 7, 8],[2, 5, 8], 8]
'min': [[0, 1, 2],[0, 3, 6], 0]
'sum': [[9, 12, 15],[3, 12, 21], 36]


By using Dictionary:
{'mean': [[3.0, 4.0, 5.0], [1.0, 4.0, 7.0], 4.0], 'variance': [[6.0, 6.0, 6.0], [0.6666666666666666, 0.6666666666666666, 0.6666666666666666], 6.666666666666667], 'standard deviation': [[2.449489742783178, 2.449489742783178, 2.449489742783178], [0.816496580927726, 0.816496580927726, 0.816496580927726], 2.581988897471611], 'max': [[6, 7, 8], [2, 5, 8], 8], 'min': [[0, 1, 2], [0, 3, 6], 0], 'sum': [[9, 12, 15], [3, 12, 21], 36]}


In [ ]:
print(calculate([0,1,2,3,4,5,6,7,10]))

One Dimensional : 
[ 0  1  2  3  4  5  6  7 10]


After converting to 3x3 matrix : 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7 10]]


'mean': [[3.0, 4.0, 5.666666666666667],[1.0, 4.0, 7.666666666666667], 4.222222222222222]
'variance': [[6.0, 6.0, 10.888888888888888],[0.6666666666666666, 0.6666666666666666, 2.888888888888889], 8.839506172839508]
'standard deviation': [[2.449489742783178, 2.449489742783178, 3.2998316455372216],[0.816496580927726, 0.816496580927726, 1.699673171197595], 2.973130702279923]
'max': [[6, 7, 10],[2, 5, 10], 10]
'min': [[0, 1, 2],[0, 3, 6], 0]
'sum': [[9, 12, 17],[3, 12, 23], 38]


By using Dictionary:
{'mean': [[3.0, 4.0, 5.666666666666667], [1.0, 4.0, 7.666666666666667], 4.222222222222222], 'variance': [[6.0, 6.0, 10.888888888888888], [0.6666666666666666, 0.6666666666666666, 2.888888888888889], 8.839506172839508], 'standard deviation': [[2.449489742783178, 2.449489742783178, 3.2998316455372216], [0.816496580927726, 0.816496580927726, 1.699673171197595], 2.973130702279923